config/routes.rb
Makeabandtome::Application.routes.draw do
  
  root :to => "bands#new"
  resources :bands

end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :cover_url
  field :cover_source
  field :cover_photo_by
  
  key :name
  
  embedded_in :band
  
  def generate_fields
    generate_name
    generate_cover
  end
  
  def generate_name
    self.name = Nokogiri::HTML(open('http://quotationspage.com/random.php3'))
      .css('.quote a').last().content().split()[-4..-1].join(' ').capitalize()
  end
  
  def generate_cover
    doc = Nokogiri::HTML(open('http://www.flickr.com/explore/'))
    
    self.cover_url = doc.css('.photo_container img:first').first().attribute('src').value()
    self.cover_source = 'http://www.flickr.com' + doc.css('.PhotoBy a:first').first().attribute('href').value()
    self.cover_photo_by = doc.css('.PhotoBy a:last b').first().content()
  end
end

app/models/band.rb
require 'open-uri'

class Band
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  key :name
  
  embeds_many :albums
  
  def self.generate
    Band.create do |band|
      band.generate_fields
    end
  end
  
  def generate_fields
    generate_name
    generate_first_album
  end
  
  def generate_name
    self.name = Nokogiri::HTML(open('http://en.wikipedia.org/wiki/Special:Random'))
      .css('.firstHeading').first().content()
  end
  
  def generate_first_album
    self.albums.new do |album|
      album.generate_fields
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    redirect_to Band.generate
  end

  def show
   @band = Band.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/_disqus.html.haml
#disqus_thread
<script type="text/javascript">
var disqus_shortname = 'makeabandtome';
(function() {
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/bands/_facebook.html.haml
.facebook-share-button
  <iframe src="http://www.facebook.com/plugins/like.php?app_id=196098540415424&amp;href&amp;send=false&amp;layout=standard&amp;width=50&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=20" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:50px; height:20px;" allowTransparency="true"></iframe>

app/views/bands/_twitter.html.haml
<a href="http://twitter.com/share" class="twitter-share-button" data-text="Check out my new Band!" data-count="none" data-via="makeabandtome">Tweet</a>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

app/views/bands/index.html.haml
= link_to "Make a band to me!", :action => "new", :controller => "bands"

app/views/bands/show.html.haml
= render partial: 'twitter'
= render partial: 'facebook'
.presentation Your New Band's first album:

.album
  %img.cover{src: @band.albums.first.cover_url}
  %label.band= @band.name
  %label.title= @band.albums.first.name

.photo-credits
  Photo by
  = link_to @band.albums.first.cover_photo_by, @band.albums.first.cover_source
  
= button_to "Make a band to me!", new_band_url, :class => 'new-band', :method => :get

= render partial: 'disqus'

app/views/layouts/application.html.haml
%html
%head
  %title Make a band to me
  = include_stylesheets :app
  = include_javascripts :app
  = csrf_meta_tag
%body
  .logo

  .content
    = yield
    
  .footer
    .explanation
      %p The idea:
      %ul
        %li Go to en.wikipedia.org and click on 'Random article'. The title of the article that appears will be your band's name;
        %li Go to quotationspage.com and click on 'Random Quotes'. The last four or five words of the last quote will be the title of your band's first album;
        %li Go to flickr.com and click on 'last 7 days'. The first photo that appears will be your first album's cover.
        %li Put it all together.

    .references
      %p References:
      %ul
        %li 
          %a.wikipedia{href: 'http://en.wikipedia.org'} Wikipedia
        %li
          %a.quotations{href: 'http://quotationspage.com'} Quotations Page
        %li
          %a.flickr{href: 'http://flickr.com'} Flickr
        %li
          %a.github{href: 'https://github.com/pirelenito/makeabandtome'} Source Code
          
    .thanks
      %p Thanks to:
      %ul
        %li 
          %a{href: 'http://www.vistaicons.com/icon/i160s0/phuzion_icon_pack.htm'} Vista Icons, for the Speaker on the logo
        %li
          %a{href: 'http://www.dinpattern.com/'} Din Patter, for the background;
        %li My friend Paulo Cesar for the idea.
        
  .copyright== Brought to you by #{link_to 'Paulo Ragonha', 'http://about.me/pirelenito'} and #{link_to 'Felipe Munhoz', 'http://about.me/munhoz'}